/* Inhalte der drei Karussells. Alle Zahlen sind aus dem Repo belegt:
   lib/data/services.ts (Preisanker), lib/data/plans.ts, lib/data/insurance.ts,
   lib/site.ts, lib/data/faq.ts. Nichts aus lib/inventory.ts – das ist
   Platzhalter und darf nicht als Tatsache auftreten. */
export const decks = [
  {
    id: "kauf", label: "Gebraucht kaufen",
    slides: [
      { kind: "hook", kicker: "Gebraucht kaufen",
        head: ["Fünf Dinge, die", "vor dem Kauf", "geprüft gehören."],
        sub: "Gebrauchter E-Scooter – worauf es wirklich ankommt." },
      { kind: "point", n: "01", title: "Der Akku",
        body: "Der teuerste Defekt am Gerät. Zellspannung und Kapazität lassen sich messen – wer nur die Restanzeige liest, sieht den Verschleiß nicht." },
      { kind: "point", n: "02", title: "Bremsen und Reifen",
        body: "Beläge und Profil sind Verschleißteile und sagen mehr über die Laufleistung als jeder Kilometerstand.",
        stat: { v: "ab 15 €", l: "Bremsbeläge" } },
      { kind: "point", n: "03", title: "Die Betriebserlaubnis",
        body: "Ohne allgemeine Betriebserlaubnis gibt es kein Versicherungskennzeichen – und damit keine Fahrt auf öffentlichen Wegen." },
      { kind: "point", n: "04", title: "Die Gewährleistung",
        body: "Beim Händler ein Jahr ab Übergabe. Unter Privatleuten wird sie in aller Regel ausgeschlossen.",
        stat: { v: "1 Jahr", l: "auf jedes Gerät von uns" } },
      { kind: "cta", head: ["Geprüft in der", "eigenen Werkstatt."],
        body: "Jedes Gerät ist ein Einzelstück: aufbereitet, gemessen und mit einem Jahr Gewährleistung übergeben." },
    ],
  },
  {
    id: "reparatur", label: "Reparatur",
    slides: [
      { kind: "hook", kicker: "Reparatur",
        head: ["Defekt heißt", "selten", "Totalschaden."],
        sub: "Was eine Reparatur kostet – und wann sie sich lohnt." },
      { kind: "point", n: "01", title: "Erst messen, dann tauschen",
        body: "Der Sicherheits-Checkup prüft sechs Positionen und sagt, was wirklich defekt ist.",
        stat: { v: "59,99 €", l: "vollständige Diagnose" } },
      { kind: "point", n: "02", title: "Die häufigsten Arbeiten",
        body: "Bremsbeläge ab 15 €, Reifenwechsel ab 25 €, Elektronik-Reparatur ab 40 €. Endpreise – nach § 19 UStG ohne Umsatzsteuer." },
      { kind: "point", n: "03", title: "Kostenvoranschlag vorher",
        body: "Vor jeder Arbeit steht der Preis fest. Es wird nichts getauscht, was Sie nicht freigegeben haben." },
      { kind: "point", n: "04", title: "Erfahrung am Gerät",
        body: "Xiaomi, Segway-Ninebot, Moover, SoFlow, Trekstor und Importgeräte. Kaum eine Bauform ist uns neu.",
        stat: { v: "500+", l: "reparierte Scooter" } },
      { kind: "cta", head: ["Bringen Sie ihn", "vorbei."],
        body: "Fachwerkstatt für Elektrokleinstfahrzeuge, Im Kampfrad 3 in Neuenstadt am Kocher." },
    ],
  },
  {
    id: "versicherung", label: "Versicherung",
    slides: [
      { kind: "hook", kicker: "Versicherung",
        head: ["Ab 6 km/h ist", "die Haftpflicht", "Pflicht."],
        sub: "Was ein E-Scooter-Kennzeichen kostet und wie lange es dauert." },
      { kind: "point", n: "01", title: "Volle Saison",
        body: "01.04.2026 bis 31.03.2027, Startpreis der günstigsten Risikoklasse.",
        stat: { v: "ab 42 €", l: "Haftpflicht, Saison" } },
      { kind: "point", n: "02", title: "Teilkasko",
        body: "Deckt zusätzlich Diebstahl ab – der häufigste Grund, warum ein Gerät nie wiederkommt.",
        stat: { v: "ab 69 €", l: "inkl. Diebstahl" } },
      { kind: "point", n: "03", title: "Das Kennzeichen",
        body: "Es kommt per Post, nicht über den Tresen. Wer zum Saisonstart fahren will, schließt rechtzeitig ab.",
        stat: { v: "5–10", l: "Werktage bis zum Kennzeichen" } },
      { kind: "point", n: "04", title: "Vermittelt als ERGO-Partner",
        body: "In der Werkstatt oder online. Wir nehmen die Angaben auf und stoßen den Antrag an." },
      { kind: "cta", head: ["Antrag", "anstoßen."],
        body: "Marke, Modell und gewünschter Zeitraum genügen. Den konkreten Beitrag melden wir zurück." },
    ],
  },
];
